New_Beginnings/Marketplace/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.views import logout


app_name = 'Marketplace'

urlpatterns = [

    url(r'^$', views.HomeView, name='home'),
    url(r'^profile/(?P<user_id>[0-9]+)/$', views.ProfileView, name='profile'),
    url(r'^item/(?P<user_id>[0-9]+)/$', views.ItemDetailsView, name='item'),
    url(r'^login/$', auth_views.login, {'template_name': 'Marketplace/login.html'},name = 'login'),
    url(r'^loggedin/$', TemplateView.as_view(template_name='Marketplace/loggedin.html')),
    url(r'^signup/$', views.signup ,name = 'signup'),
    url(r'^logout/$', logout, {'next_page':'Marketplace:login'}, name = 'logout'),
    url(r'^post/$', views.PostItemView.as_view() ,name = 'post'),
    url(r'^offer/(?P<item_id>[0-9]+)/$', views.MakeOfferView.as_view() ,name = 'offer'),
    url(r'^delete/(?P<offer_id>[0-9]+)/$', views.delete ,name = 'delete'),
    url(r'^update/(?P<item_id>[0-9]+)/(?P<offer_id>[0-9]+)/$', views.update.as_view() ,name = 'update'),
    url(r'^decline/(?P<user_id>[0-9]+)/(?P<offer_id>[0-9]+)/$', views.decline.as_view() ,name = 'decline'),
    url(r'^accept/(?P<user_id>[0-9]+)/(?P<item_id>[0-9]+)/(?P<offer_id>[0-9]+)/$', views.accept.as_view() ,name = 'accept')
]

New_Beginnings/New_Beginnings/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^Marketplace/', include('Marketplace.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

New_Beginnings/Marketplace/models.py
from django.db import models
from django.contrib.auth.models import User
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.

#OneToOne relation with User model from Django
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    FirstName = models.CharField(max_length=30)
    LastName = models.CharField(max_length=30)
    birthdate = models.DateField(null=True, blank=True)
    is_Student = models.BooleanField(default=True)
    degreeProgram = models.CharField(max_length=30, null=True, blank=True)
    office = models.CharField(max_length=30, null=True, blank=True)
    displayPic = models.FileField(blank=True, null=True)

    @receiver(post_save, sender=User)
    def update_user_profile(sender, instance, created, **kwargs):
        if created:
            Profile.objects.create(user=instance)
        instance.profile.save()

    def __str__(self):
        return self.FirstName +" "+self.LastName


class Tag(models.Model):
    text = models.CharField(max_length = 25)

    def __str__(self):
        return self.text

class Item(models.Model):
    profile = models.ForeignKey(Profile, null = True, blank=False)
    item_name = models.CharField(max_length = 40)
    thumbnail = models.ImageField(blank=True,null=True)
    tag = models.ManyToManyField(Tag, blank = True)
    is_secondHand = models.BooleanField(default=False)
    is_academic = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now_add=True)
    quantity = models.IntegerField(default=1)
    course_name = models.CharField(max_length=30,default="none",blank=True)

    def __str__(self):
        return self.item_name

class Offer(models.Model):
    user = models.ForeignKey(Profile, on_delete=models.CASCADE)
    item = models.ForeignKey(Item, on_delete=models.CASCADE, related_name="orig_post")
    is_Amount = models.BooleanField(default=False)
    amount_offer = models.IntegerField(default=0,null=True,blank=True)
    item_offer = models.ForeignKey(Item, on_delete=models.CASCADE, null=True, blank=True)
    accepted = models.BooleanField(default=False)
    reason = models.CharField(max_length = 200, blank=True)

    def __str__(self):
        return self.user.FirstName + self.user.LastName + ' offered on ' + self.item.item_name

New_Beginnings/Marketplace/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import *
from django.forms import ModelForm
class LoginForm(forms.Form):
    user= forms.CharField(max_length = 50)
    password = forms.CharField(widget = forms.PasswordInput())

class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False)
    last_name = forms.CharField(max_length=30, required=False)
    birthdate = forms.DateField(required=True, help_text='Required. Format: YYYY-MM-DD')
    Student = forms.BooleanField(required=False)
    degree = forms.CharField(max_length=30, required=False)
    office = forms.CharField(max_length=30, required=False)

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name' ,'birthdate','Student','degree','office','password1','password2',)

class PostItemForm(forms.ModelForm):
    item_name = forms.CharField()
    thumbnail = forms.FileField()
    tag = forms.ModelMultipleChoiceField(queryset=Tag.objects.all())
    is_academic = forms.BooleanField(required=False)
    quantity = forms.IntegerField()
    course_name = forms.CharField()

    class Meta:
        model = Item
        fields = {'item_name','thumbnail','tag','is_academic','quantity','course_name'}

class MakeOfferForm(forms.ModelForm):
    is_Amount = forms.BooleanField(required=False)
    amount_offer = forms.IntegerField(required=False)
    reason = forms.CharField(required=True)

    class Meta:
        model = Offer
        fields = {'is_Amount','amount_offer','item_offer','reason'}

New_Beginnings/Marketplace/views.py
from django.shortcuts import *
from django.views import generic
from django.views import View
from django.views.generic import TemplateView
from .models import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.
from .forms import *
from django.urls import reverse, reverse_lazy

def HomeView(request):
    all_items_list = Item.objects.all()
    template_name = 'Marketplace/home.html'
    context_object_name = 'all_items'
    query = request.GET.get("q")
    print(query)
    if query:
        all_items_list = all_items_list.filter(tag__text__icontains=query)
    paginator = Paginator(all_items_list, 10)
    page = request.GET.get('page')
    try:
        all_items = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        all_items = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        all_items = paginator.page(paginator.num_pages)

    if request.user.is_authenticated():
        current_user = request.user
        user_id = get_object_or_404(Profile, user = request.user).id
        offers = list(Offer.objects.all())
        return render(request, 'Marketplace/home.html', {'all_items':all_items, 'current_user': current_user, 'pk':user_id,'offers':offers})
    else:
        return render(request, 'Marketplace/home.html', {'all_items':all_items})

@login_required
def ProfileView(request, user_id):
    user = get_object_or_404(Profile, pk = user_id)
    items = list(Item.objects.filter(profile = user_id))
    query = request.GET.get("q")
    offers = list(Offer.objects.all())
    if query:
        return redirect('/Marketplace/?q=' + query + "#")
    return render(request, 'Marketplace/profile.html', {'user': user, 'items':items,'offers':offers})

def ItemDetailsView(request, user_id):
    item = get_object_or_404(Item, pk=user_id)
    if request.user.is_authenticated():
        id = get_object_or_404(Profile, user=request.user).id
        print("hello world")
        #print(get_object_or_404(Offer,item=get_object_or_404(Item,pk=user_id)))
        offers = list(Offer.objects.filter(item=get_object_or_404(Item,pk=user_id)))
        print(offers)
        return render(request, 'Marketplace/detailslogged.html', {'item': item, 'pk':id,'offers':offers})
    else:
        return render(request, 'Marketplace/details.html', {'item': item})

def LoginView(request):
    username = "Not Logged In"
    if request.method == "POST":
        loginForm = LoginForm(request.POST)
        if loginForm.is_valid():
            username = loginForm.cleaned_data['username']
            user_id = request.user_id
    else:
        loginForm = LoginForm()

    return render(request, 'Marketplace/login.html', {"username": username})

class PostItemView(View):
    def get(self,request):
        postForm = PostItemForm()
        user_id = get_object_or_404(Profile, user = request.user).id
        context = {
            "title": "Hello world",
            "form": postForm,
            "pk":user_id
        }
        return render(request,'Marketplace/post.html',context)

    def post(self,request):
        postForm = PostItemForm(request.POST,request.FILES)
        if postForm.is_valid():
            temp = postForm.save(commit=False)
            temp.is_secondHand = 1
            temp.profile = get_object_or_404(Profile,user=request.user)
            temp.save()
            return redirect('Marketplace:home')
        else:
            print(postForm.errors.as_data())

        user_id = get_object_or_404(Profile, user = request.user).id
        return render(request, 'Marketplace/post.html', {'pk':user_id})

class MakeOfferView(View):
    def get(self,request,item_id):
        offerForm = MakeOfferForm()
        user_id = get_object_or_404(Profile, user = request.user).id
        offerForm.fields['item_offer'].queryset = Item.objects.filter(profile=get_object_or_404(Profile, user = request.user))
        print(get_object_or_404(Profile, user = request.user))
        context = {
            "form": offerForm,
            "pk": user_id
        }
        return render(request,'Marketplace/offer.html',context)
    def post(self,request,item_id):
        offerForm = MakeOfferForm(request.POST)
        if offerForm.is_valid():
            temp = offerForm.save(commit=False)
            temp.user = get_object_or_404(Profile,user=request.user)
            temp.item = get_object_or_404(Item,pk=item_id)
            temp.save()
            return redirect('Marketplace:home')
        else:
            print(offerForm.errors.as_data())

class UserFormView(generic.View):
    form_class = SignUpForm
    template_name = 'Marketplace/signup.html'

    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():

            user = form.save(commit=False)

            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            user = authenticate(username = username, password = password)

            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('Marketplace/home.html')

        return render(request, self.template_name, {'form': form})

def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()

            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user.profile.birthdate = form.cleaned_data.get('birthdate')
            user.profile.is_Student = form.cleaned_data.get('Student')
            user.profile.degreeProgram = form.cleaned_data.get('degree')
            user.profile.office = form.cleaned_data.get('office')
            user.profile.FirstName = form.cleaned_data.get('first_name')
            user.profile.LastName = form.cleaned_data.get('last_name')
            user.save()
            user = authenticate(username=username, password = raw_password)
            login(request,user)
            return redirect('Marketplace:home')
    else:
        form = SignUpForm()

    return render(request, 'Marketplace/signup.html', {'form':form})

def logoutView(request):
    logout(request)

def delete(request,offer_id):
    Offer.objects.filter(pk=offer_id).delete()
    print("hello")
    return redirect('Marketplace:home')

class update(View):
    def get(self,request, item_id,offer_id):
        Offer.objects.filter(pk=offer_id).delete()
        offerForm = MakeOfferForm()
        user_id = get_object_or_404(Profile, user=request.user).id
        offerForm.fields['item_offer'].queryset = Item.objects.filter(
            profile=get_object_or_404(Profile, user=request.user))
        print(get_object_or_404(Profile, user=request.user))
        context = {
            "form": offerForm,
            "pk": user_id
        }
        return render(request, 'Marketplace/update.html', context)

    def post(self, request, item_id, offer_id):
        offerForm = MakeOfferForm(request.POST)
        if offerForm.is_valid():
            temp = offerForm.save(commit=False)
            temp.user = get_object_or_404(Profile, user=request.user)
            temp.item = get_object_or_404(Item, pk=item_id)
            temp.save()
            return redirect('Marketplace:home')
        else:
            print(offerForm.errors.as_data())

class decline(View):
    def get(self,request,user_id,offer_id):
        Offer.objects.filter(pk=offer_id).delete()
        return redirect('/Marketplace/profile/' + user_id + "/")
    def post(self,request,user_id,offer_id):
        return redirect('Marketplace/profile/' + user_id + "/")

class accept(View):
    def get(self,request,user_id,item_id,offer_id):
        Offer.objects.filter(pk=offer_id).delete()
        Item.objects.filter(pk=item_id).delete()
        return redirect('/Marketplace/profile/' + user_id + "/")
    def post(self,request,user_id,item_id,offer_id):
        return redirect('Marketplace/profile/' + user_id + "/")

New_Beginnings/Marketplace/templates/Marketplace/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New Beginnings{% endblock %}</title>
    {% load staticfiles %}
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:600i|Permanent+Marker" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" type = "text/css" href="{% static 'Marketplace/style.css' %}"> <!-- references your static directory -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Concert+One|Lobster" rel="stylesheet">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    <!-- navbar inverse changes it to dark theme-->
    <nav class = "navbar navbar-light">
        <div class = "container-fluid">
            <!-- the Header -->
            <div class = "navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <!-- icon that shows when resizing -->

                </button>
                <a class="navbar-brand" href="{% url 'Marketplace:home' %}">New Beginnings</a>

            </div>
            <!-- Items -->
            <!-- id = topNavBar so that when resized too low, everything in the div will be hidden and topNavBar will show-->
            <div class = "collapse navbar-collapse" id = "topNavBar">
              {% if user.is_authenticated %}
                <ul class="nav navbar-nav">
                    <!-- active darkens the item -->
                    <li class = "active">
                        <a href="{% url 'Marketplace:home' %}">
                            <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                            Home
                        </a>
                    </li>

                    <li class = "">
                        <a href="{% url 'Marketplace:profile' pk %}" >
                            <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                            Profile
                        </a>
                    </li>

                    <li class = "">
                        <a href="{% url 'Marketplace:post' %}">
                            <span class="glyphicon glyphicon-post" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                            Post
                        </a>
                    </li>
                    <li class = "">
                        <a href="" data-toggle="modal" data-target="#myModal">
                            <span class="glyphicon glyphicon-post" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                            My Offers
                        </a>
                    </li>
                </ul>

                <!-- The search bar navbar-left so that elements will float left -->
                <form class = "navbar-form navbar-left" role="search" method="get" action="#">
                    <div class="form-group">
                        <!-- query is the variable for storage of the string that people type in on search bar -->
                        <input type = "text" class = "form-control" name = "q" value="" placeholder="Search by tags"/>
                        <button type = "submit" class = "btn btn-default">Search</button>
                    </div>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class = "">
                        <a href = "{% url 'Marketplace:logout' %}">
                            <span class="glyphicon glyphicon-log-out" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                            Logout
                        </a>
                    </li>
                </ul>
                {% else %}
                  <ul class="nav navbar-nav">
                      <!-- active darkens the item -->
                      <li class = "active">
                          <a href="{% url 'Marketplace:home' %}">
                              <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                              Home
                          </a>
                      </li>
                  </ul>

                  <!-- The search bar navbar-left so that elements will float left -->
                  <form class = "navbar-form navbar-left" role="search" method="get" action="#">
                      <div class="form-group">
                          <!-- query is the variable for storage of the string that people type in on search bar -->
                          <input type = "text" class = "form-control" name = "q" value="" placeholder="Search by tags"/>
                          <button type = "submit" class = "btn btn-default">Search</button>
                      </div>
                  </form>

                  <ul class="nav navbar-nav navbar-right">
                      <li class ="">
                          <a href = "{% url 'Marketplace:login' %}">
                              <span class = "glyphicon glyphicon-log-in" aria-hidden = "true"></span>
                                  Login
                          </a>
                      </li>
                      <li class = "">
                          <a href="{% url 'Marketplace:signup' %}">
                              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                              Register
                          </a>
                      </li>

                  </ul>
                  {% endif %}
            </div>
        </div>
    </nav>

    <!-- tells that we will include a block of code later on after the above -->
    {% block body %}

    {% endblock %}
</body>
</html>

New_Beginnings/Marketplace/templates/Marketplace/details.html
{% extends 'Marketplace/detailsPage.html' %}
{% block body %}
    {% if item %}
         <div class = "container">
            <a href = "{% url 'Marketplace:profile' item.profile.id %}">
                <h1><span>{{ item.profile.FirstName }}</span> &nbsp <span>{{ item.profile.LastName }}</span></h1>
            </a>
             <h2>{{ item.item_name }}</h2>
            <img src="{{ item.thumbnail.url }}" class = "detailThumbnail">
            {% if item.is_secondHand %}
                <p>Condition: Secondhand</p>
            {% else %}
                <p>Condition: Brand-New</p>
            {% endif %}

            {% if item.profile.is_Student %}
                <p>Use: Academic</p>
            {% else %}
                <p>Use: Office</p>
            {% endif %}

            {% if item.tag %}
                <p>Tags: </p>
                <ul>
                {% for Tag in item.tag.all %}
                    <li>
                        {{ Tag.text }}
                    </li>
                {% endfor %}
                </ul>
            {% endif %}
         </div>
    {% endif %}
{% endblock %}

New_Beginnings/Marketplace/templates/Marketplace/detailslogged.html
{% extends 'Marketplace/base.html' %}
{% block body %}
    {% if item %}
    <div class="container">
        <div class="text-center">
         <a class = "container">
            <a href = "{% url 'Marketplace:profile' item.profile.id %}">
                <h1 style="font-family: 'Open Sans', sans-serif; font-size:25px;"><span>{{ item.profile.FirstName }}</span> <span>{{ item.profile.LastName }}</span></h1>
            </a>
             <h2 style="font-family: 'Pacifico', cursive;">{{ item.item_name }}</h2>
            <img src="{{ item.thumbnail.url }}" class = "detailThumbnail" height = 450px width = 450px>
            {% if item.is_secondHand %}
                <p>Condition: Secondhand</p>
            {% else %}
                <p>Condition: Brand-New</p>
            {% endif %}

            {% if item.profile.is_Student %}
                <p>Use: Academic</p>
            {% else %}
                <p>Use: Office</p>
            {% endif %}

            {% if item.tag %}
                <p>Tag/s: {{ item.tag.all|join:", " }}</p>
            {% endif %}
            <!-- <a href="{% url 'Marketplace:offer' item.pk %}"> -->
            {% if offers %}
            {% else %}
                {% if pk != item.profile.id %}
                    <a style="font-family: 'Open Sans', sans-serif;" href="{% url 'Marketplace:offer' item.pk %}">Make an Offer</button>
                {% endif %}
            {% endif %}
                <!--{% for offer in offers %}-->
                    <!--{% if forloop.last and offer.item != item %}-->
                        <!--<a style="font-family: 'Open Sans', sans-serif;" href="{% url 'Marketplace:offer' item.pk %}">Make an Offer</button>-->
                    <!--{% elif offer.item == item %}-->
                    <!--{% endif %}-->
                <!--{% endfor %}-->
            </a>
                <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

              <!-- Modal content-->
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                  <h3 class="modal-title">Your Offers</h3>
                </div>
                <div class="modal-body">
                    {% if offers %}
                        {% for offer in offers %}
                            {% if forloop.first %}
                                <h4>{{offer}}</h4>
                                {% if offer.is_Amount %}
                                    <h4>Amount offered: {{offer.amount_offer}}</h4>
                                {% else %}
                                    <h4>Exchange for: {{offer.item_offer}}</h4>
                                {% endif %}
                                    <h4>Reason: {{offer.reason}}</h4>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                      {% if pk != item.profile.id %}
                        <h4>You have no offers for this item!</h4>
                      {% else %}
                        <h4>This is an item you posted!</h4>
                      {% endif %}
                    {% endif %}
                </div>
                <div class="modal-footer">
                  <div class="text-center">
                    {% if offers %}
                        <a>
                            <button type="submit" class="btn btn-success" data-dismiss="modal" data-toggle="modal" data-target="#confirm-update">Update</button>
                        </a>
                        <a>
                            <button type="submit" class="btn btn-danger" data-dismiss="modal" data-toggle="modal" data-target="#confirm-cancel">Cancel</button>
                        </a>
                    {% endif %}

                </div>

                </div>
                </div>
              </div>

            </div>
              <!-- Modal 2 -->
              <div id="confirm-update" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <h4>Are you sure you want to update?</h4>
                    </div>
                    <div class="modal-footer">
                      <div class="text-center">
                      {% if offers %}
                          {% for offer in offers %}
                            {% if forloop.first %}
                                <a href="{% url 'Marketplace:update' item.pk offer.pk %}">
                                    <button type="button" class="btn btn-success">Yes</button>
                                </a>
                            {% endif %}
                          {% endfor %}
                      {% endif %}
                      <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
             <div id="confirm-cancel" class="modal fade" role="dialog">
                <div class="modal-dialog">
                  <div class="modal-content">
                    <div class="modal-header">
                      <button type="button" class="close" data-dismiss="modal">&times;</button>
                    </div>
                    <div class="modal-body">
                      <h4>Are you sure you want to cancel?</h4>
                    </div>
                    <div class="modal-footer">
                      <div class="text-center">
                      {% if offers %}
                          {% for offer in offers %}
                            {% if forloop.first %}
                                <a href="{% url 'Marketplace:delete' offer.pk %}">
                                    <button type="button" class="btn btn-success">Yes</button>
                                </a>
                            {% endif %}
                          {% endfor %}
                      {% endif %}
                        <!--<button type="button" class="btn btn-success" data-dismiss="modal">Yes</button>-->
                      <button type="button" class="btn btn-danger" data-dismiss="modal">No</button>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
          </div>
         </div>
        </div>
    {% endif %}
{% endblock %}

New_Beginnings/Marketplace/templates/Marketplace/loginPage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}New Beginnings{% endblock %}</title>
    {% load staticfiles %}
    <link rel = "stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"/>
    <link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link rel="stylesheet" type = "text/css" href="{% static 'Marketplace/style.css' %}"> <!-- references your static directory -->
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css?family=Abril+Fatface|Concert+One|Lobster" rel="stylesheet">
</head>
<body>
    <!-- navbar inverse changes it to dark theme-->
    <nav class = "navbar navbar-light">
        <div class = "container-fluid">
            <!-- the Header -->
            <div class = "navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <span class = "icon-bar"></span>
                    <!-- icon that shows when resizing -->

                </button>
                <a class="navbar-brand" href="{% url 'Marketplace:home' %}">New Beginnings</a>

            </div>
            <!-- Items -->
            <!-- id = topNavBar so that when resized too low, everything in the div will be hidden and topNavBar will show-->
            <div class = "collapse navbar-collapse" id = "topNavBar">
              <ul class="nav navbar-nav">
                  <!-- active darkens the item -->
                  <li class = "active">
                      <a href="{% url 'Marketplace:home' %}">
                          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                          Home
                      </a>
                  </li>
              </ul>
                  <ul class="nav navbar-nav navbar-right">
                      <li class = "">
                          <a href="{% url 'Marketplace:signup' %}">
                              <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; <!-- non breaking space -->
                              Register
                          </a>
                      </li>
                  </ul>
            </div>
        </div>
    </nav>

    <!-- tells that we will include a block of code later on after the above -->
    {% block body %}

    {% endblock %}
</body>
</html>